# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: cms_development
  pool: 5
  timeout: 5000
  username: magragosh
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: cms_test
  pool: 5
  timeout: 5000
  username: magragosh
  password: 

